export const SET_CURRENT_MONTH_NAME = 'SET_CURRENT_MONTH_NAME';
export const SET_CURRENT_MONTH = 'SET_CURRENT_MONTH';
export const SET_CURRENT_YEAR = 'SET_CURRENT_YEAR';
export const SET_TITLE = 'SET_TITLE';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_IS_RECURRING = 'SET_IS_RECURRING';
export const SET_IS_ENDING = 'SET_IS_ENDING';
export const SET_EXPENSE_DATE = 'SET_EXPENSE_DATE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const CLEAR_FIELDS = 'CLEAR_FIELDS';
export const SELECT_FREQUENCY = 'SELECT_FREQUENCY';
export const SET_INITIAL_EXPENSES = 'SET_INITIAL_EXPENSES';

